#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp32-client
# EXCLUDE_COMPONENTS := coap bt esp_http_client esp_http_server esp_https_ota esp_https_server \
#                       fatfs freemodbus mqtt protobuf-c spiffs ulp tcp_transport esp-tls nghttp protocomm \
# 					  wifi_provisioning wear_levelling sdmmc

include $(IDF_PATH)/make/project.mk

